swagger:
  api-version: 1.0
  enabled:    true
  title: Ara API
  description: Arya APIs
  useDefaultResponseMessages: false
  enableUrlTemplating: false
  deepLinking: true
  defaultModelsExpandDepth: 1
  defaultModelExpandDepth: 1
  displayOperationId: false
  displayRequestDuration: false
  filter: false
  maxDisplayedTags: 0
  showExtensions: false


agnext.kyf:
  s3: # S3 settings
    environment: im-data # dev-specx for development & prod-specx for production
    bucket: agnext-jasmine
    key: AKIAILBHPDQCDAA2F4WA
    secret: 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
    url: https://agnext-jasmine.s3.us-east-2.amazonaws.com/ 

#security:
#  jwt:
#    key-store: classpath:keystore.jks
#    key-store-password: letmein
#    key-pair-alias: mytestkey
#    key-pair-password: changeme
#    public-key: classpath:public.txt


  #Local DB
#  url: jdbc:mysql://localhost:3306/nafed_visio?serverTimezone=UTC&autoReconnect=true
#  driverClassName: com.mysql.jdbc.Driver
#  username: root
#  password: piyush

spring:
  profiles:
    active: dev
  jackson:
    serialization:
      INDENT_OUTPUT: true 

spring.jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
#  generate-ddl: true
  properties:
    hibernate.show_sql: true
#    hibernate.generate_statistics: true
#    hibernate.ddl-auto: create-update
#    hibernate.use_sql_comments: true
#    hibernate.format_sql: true


notification:
   serverUrl: http://23.98.216.140:9456/notification
   emailFrom: support@agnext.in
   emailAdmin: mitesh@agnext.in

tenant-details: 
   name: Nafed
ag:
  paymentEnvironmentId: 8  
  
module-builder:
 aiCustomer: ai@agnext.in      
  
email-config:
  send-email: false

#Analytics COnfiguration
analyticsconfig:
  analytics:
    moisturecontent:
      - moisture
      - moisture content
      - moisturecontent
      - Moisture
      - MoistureContent

    foreignmatter:
      - foreignmatter
      - foreignmattera
      - foreignmatters
      - fm
      - f m
      - foreign matter

    admixture:
      - admixture
      - ad-mixture

    damaged:
      - damaged
      - damaged pods
      - damaged pulses

    weevilled:
      - weevilled
      - weevilled pulses
      - weevilled pods

    shrivelledandimmature:
      - shrivelled & immature
      - Shrivelled & immature
      - shrivelled & immature pulses
      - shrivelled_and_immature pulses
      - shrivelledimmaturepulses
      - Shrivelled & immature pulses
      - shrivelled&immature
      - shrivelledandimmature
      - shrivelledAndImmature
      - shrivelled_and_immature
      - shrivelled & immature pods
      - Shrivelled & immature pods
      - shrivelled_and_immature pods

    slightlydamaged:
      - slightlydamaged
      - Slightlydamaged
      - slightly damage pulses
      - slightly damage pods
      - slightlydamagepulses
      - slightlydamagepods

    podsofothervariety:
      - podsofothervariety
      - pods of other
      - pods of other varieties
      - podsofothervariety
      - podsofothervar

    shelling:
      - Shelling
      - shelling 
      - shelling kernel
      - shellingkernel
      - Shelling kernel
      - Shelling Kernel
      - ShellingKernel
      
    damagedandweevilled:
      - damaged & weevilled
      - damagedandweevilled
      - damaged_and_weevilled
      - damaged and weevilled 
      - Damaged & Weevilled
      - Damaged&Weevilled
      - DamagedAndWeevilled
      - damaged&weevilled
     
    immature:
      - immature   

    otherfoodgrains:
      - other food grains
      - other food grain
      - otherfoodgrains
      - otherfoodgrain
      
    smallatrophiedseeds:
      - small atrophied seeds
      - small atrophied seed
      - smallatrophiedseeds
      - smallatrophiedseed
      
    splitcracked:
      - Splitcracked
      - splitcracked
      - SplitCracked
      - splitCracked
      - Split or Cracked seeds
      - split or cracked seeds
      - Split or cracked seeds
      - split or Cracked seeds


---

spring:
  profiles: dev

server:
  port: 9982
  servlet.context-path: /

logging:
  level:
    org.springframework: ERROR
    com.agnext: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%C){cyan} %clr(:){faint} %m%n%wex"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/nafed/nafed-dev.log

#spring.datasource:
#  url: jdbc:mysql://mysql-server-in.mysql.database.azure.com:3306/nafed_visio?serverTimezone=UTC&autoReconnect=true
#  driverClassName: com.mysql.jdbc.Driver
#  username: agnextadmin@mysql-server-in
#  password: Agnext@2019#
  
spring.cofco.datasource:
  jdbcUrl: jdbc:mysql://mysql-server-in.mysql.database.azure.com:3306/cofco_devops?serverTimezone=UTC&autoReconnect=true
  username: agnextadmin@mysql-server-in
  password: Agnext@2019#
  driver-class-name: com.mysql.jdbc.Driver

spring.jpa.show-sql: true

spring.nafed.datasource:
  jdbcUrl: jdbc:mysql://mysql-server-in.mysql.database.azure.com:3306/nafed_devops?serverTimezone=UTC&autoReconnect=true
  username: agnextadmin@mysql-server-in
  password: Agnext@2019#
  driver-class-name: com.mysql.jdbc.Driver

spring.autoconfigure.exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration


iam.url:
  access: http://13.71.36.247:9982/oauth/token?grant_type=authorization_code&code=
  userAccess: http://13.71.36.247:9982/api/user/

---

spring:
  profiles: qa

server:
  port: 9994
  servlet.context-path: /

logging:
  level:
    org.springframework: ERROR
    com.agnext: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%C){cyan} %clr(:){faint} %m%n%wex"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/nafed/nafed-qa.log

spring.datasource:
  url: jdbc:mysql://mysql-server-in.mysql.database.azure.com:3306/nafed_dev?serverTimezone=UTC&autoReconnect=true
  driverClassName: com.mysql.jdbc.Driver
  username: agnextadmin@mysql-server-in
  password: Agnext@2019#

iam.url:
  access: http://13.71.36.247:9994/oauth/token?grant_type=authorization_code&code=
  userAccess: http://13.71.36.247:9994/api/user/

---

spring:
  profiles: prod

server:
  port: 9991
  servlet.context-path: /

logging:
  level:
    org.springframework: ERROR
    com.agnext: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%C){cyan} %clr(:){faint} %m%n%wex"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/nafed/nafed-prod.log

spring.datasource:
  url: jdbc:mysql://mysql-server-in.mysql.database.azure.com:3306/nafed_pilot?serverTimezone=UTC&autoReconnect=true
  driverClassName: com.mysql.jdbc.Driver
  username: agnextadmin@mysql-server-in
  password: Agnext@2019#

iam.url:
  access: http://13.71.36.247:9991/oauth/token?grant_type=authorization_code&code=
  userAccess: http://13.71.36.247:9991/api/user/